"""Extract plain text from stored resumes and apply in-place tailor edits."""

from __future__ import annotations

import logging
import re
import zipfile
from io import BytesIO
from pathlib import Path

from docx import Document
from docx.oxml import OxmlElement
from docx.text.paragraph import Paragraph
from pypdf import PdfReader

from backend.app.core.errors import AppError
from backend.app.services import resume_ocr

_SUMMARY_HEADERS = frozenset(
    {"summary", "professional summary", "profile", "about", "about me", "objective", "career summary"}
)
_SKILLS_HEADERS = frozenset(
    {"skills", "technical skills", "core competencies", "technologies", "tools", "tech stack"}
)
_EDUCATION_HEADERS = frozenset(
    {"education", "academic background", "qualifications", "academics", "education & training"}
)
_EXPERIENCE_HEADERS = frozenset(
    {"experience", "work experience", "professional experience", "employment", "employment history", "work history"}
)
_LINKEDIN_RE = re.compile(r"https?://(?:www\.)?linkedin\.com/in/[a-zA-Z0-9_-]+/?", re.I)
_URL_RE = re.compile(r"https?://[^\s)>]+", re.I)
_AI_BUZZ_RE = re.compile(
    r"\b("
    r"results[- ]driven|detail[- ]oriented|passionate|dynamic|synerg(?:y|ies)|leverag(?:e|ing|ed)|"
    r"spearhead(?:ed|ing)?|cutting[- ]edge|proven track record|eager to contribute|excited to|"
    r"adept at|seasoned professional|thought leader|best[- ]in[- ]class|utiliz(?:e|es|ed|ing)|"
    r"robust solution|game[- ]changer|go[- ]to person|self[- ]starter|team player|"
    r"tailored (?:for|to)|(?:this|the) job description|as an ai|chatgpt|generated by"
    r")\b",
    re.I,
)


def _pdf_native_text(path: Path) -> str:
    reader = PdfReader(str(path))
    parts = []
    for page in reader.pages:
        parts.append(page.extract_text() or "")
    return "\n".join(parts).strip()


def extract_text_with_source(path: Path, file_type: str, *, emphasize_ocr: bool = False) -> tuple[str, str]:
    """
    Returns (plain_text, source) where source is pdf_text, ocr, pdf_text+ocr, or docx.
    PDFs use OCR when embedded text is missing or too sparse (scanned resumes).
    With emphasize_ocr=True (profile intake), OCR always runs for PDFs and is merged with native text.
    """
    if file_type == "pdf":
        native = _pdf_native_text(path)
        need_ocr = emphasize_ocr or not resume_ocr.text_usable(native)
        if not need_ocr:
            return native, "pdf_text"
        try:
            scanned = resume_ocr.ocr_pdf(path)
            merged = resume_ocr.merge_pdf_text(native, scanned)
            if resume_ocr.text_usable(merged):
                if not native.strip():
                    return merged, "ocr"
                if not resume_ocr.text_usable(native):
                    return merged, "ocr"
                return merged, "pdf_text+ocr"
            if scanned:
                return merged or scanned, "ocr"
        except Exception as exc:
            logging.getLogger(__name__).warning("Resume OCR failed for %s: %s", path, exc)
        if native:
            return native, "pdf_text"
        return "", "pdf_text"
    if file_type == "docx":
        doc = Document(str(path))
        return "\n".join(p.text for p in doc.paragraphs if p.text).strip(), "docx"
    raise AppError("INVALID_FILE", f"Unsupported resume type: {file_type}", 422)


def extract_text(path: Path, file_type: str) -> str:
    text, _ = extract_text_with_source(path, file_type)
    return text


def guess_skills_from_text(text: str, profile_skills: list[str]) -> list[str]:
    """Heuristic skill list: profile skills plus tokens from a Skills section."""
    found: list[str] = []
    seen: set[str] = set()
    for s in profile_skills or []:
        key = s.strip()
        if key and key.lower() not in seen:
            seen.add(key.lower())
            found.append(key)
    lower = text.lower()
    for header in ("skills", "technical skills", "core competencies"):
        idx = lower.find(header)
        if idx >= 0:
            chunk = text[idx : idx + 2500]
            for part in re.split(r"[,|\n•·]", chunk):
                token = part.strip(" :-\t")
                if 2 <= len(token) <= 64 and token.lower() not in seen:
                    seen.add(token.lower())
                    found.append(token)
            break
    return found[:80]


def humanize_line(text: str) -> str:
    """Remove common AI-resume tells; keep meaning and facts."""
    line = re.sub(r"\s+", " ", (text or "").strip())
    if not line:
        return line
    line = _AI_BUZZ_RE.sub("", line)
    line = re.sub(r"\s{2,}", " ", line)
    line = line.replace(" ;", ";").strip(" ,.;")
    return line


def section_kind(line: str) -> str | None:
    t = re.sub(r"[^a-zA-Z\s&]", "", (line or "").strip()).lower()
    if t in _SUMMARY_HEADERS:
        return "summary"
    if t in _SKILLS_HEADERS:
        return "skills"
    if t in _EDUCATION_HEADERS:
        return "education"
    if t in _EXPERIENCE_HEADERS:
        return "experience"
    return None


def _lines(text: str) -> list[str]:
    return [ln.strip() for ln in (text or "").splitlines()]


def _slice_section(lines: list[str], header_kind: str, *, stop_kinds: frozenset[str]) -> list[str]:
    start = None
    for i, line in enumerate(lines):
        if section_kind(line) == header_kind:
            start = i + 1
            break
    if start is None:
        return []
    out: list[str] = []
    for line in lines[start:]:
        kind = section_kind(line)
        if kind and kind in stop_kinds:
            break
        if line:
            out.append(line)
    return out


def _parse_education_lines(chunk: list[str]) -> list[dict]:
    entries: list[dict] = []
    block: list[str] = []
    for line in chunk:
        if re.match(r"^(19|20)\d{2}\b", line) or re.search(r"\b(19|20)\d{2}\s*[-–—]", line):
            if block:
                entries.append(_education_from_block(block))
            block = [line]
        elif line.lower().startswith(("b.", "b.s", "b.a", "m.", "m.s", "mba", "phd", "bachelor", "master")):
            if block:
                entries.append(_education_from_block(block))
            block = [line]
        else:
            block.append(line)
    if block:
        entries.append(_education_from_block(block))
    return [e for e in entries if e.get("school") or e.get("degree")][:15]


def _education_from_block(block: list[str]) -> dict:
    degree = field = school = ""
    years = re.findall(r"\b(19|20)(\d{2})\b", " ".join(block))
    end_year = start_year = ""
    if years:
        nums = sorted(int(a + b) for a, b in years)
        start_year = str(nums[0]) if nums else ""
        end_year = str(nums[-1]) if nums else ""
    for line in block:
        low = line.lower()
        if any(x in low for x in ("bachelor", "master", "b.", "b.s", "m.", "mba", "ph.d", "degree")):
            degree = line[:255]
        elif not school and len(line) > 3 and not re.match(r"^(19|20)\d{2}", line):
            if degree and not field and line != degree:
                field = line[:255]
            elif not degree:
                degree = line[:255]
            else:
                school = line[:255]
        elif not school:
            school = line[:255]
    return {
        "school": school,
        "degree": degree,
        "field": field,
        "start_year": start_year,
        "end_year": end_year,
    }


def _parse_experience_lines(chunk: list[str]) -> list[dict]:
    entries: list[dict] = []
    block: list[str] = []
    for line in chunk:
        if re.search(r"\b(19|20)\d{2}\s*[-–—]", line) or re.search(r"\b(present|current)\b", line.lower()):
            if block:
                entries.append(_work_from_block(block))
            block = [line]
        elif line.startswith(("•", "-", "·", "*")) and block:
            block.append(line.lstrip("•·-* ").strip())
        else:
            if block and len(block) >= 2 and section_kind(line) is None:
                block.append(line)
            elif not block:
                block = [line]
            else:
                entries.append(_work_from_block(block))
                block = [line]
    if block:
        entries.append(_work_from_block(block))
    return [e for e in entries if e.get("title") or e.get("company")][:20]


def _work_from_block(block: list[str]) -> dict:
    title = company = location = start = end = ""
    bullets: list[str] = []
    date_line = next((ln for ln in block if re.search(r"(19|20)\d{2}", ln)), "")
    if date_line:
        m = re.search(
            r"((?:19|20)\d{2}|(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\.?\s*(?:19|20)\d{2})"
            r"\s*[-–—]\s*"
            r"((?:19|20)\d{2}|(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\.?\s*(?:19|20)\d{2}|present|current)",
            date_line,
            re.I,
        )
        if m:
            start, end = m.group(1).strip()[:32], m.group(2).strip()[:32]
    body = [ln for ln in block if ln != date_line]
    if body:
        title = body[0][:255]
    if len(body) > 1:
        second = body[1]
        if " at " in second.lower():
            parts = re.split(r"\s+at\s+", second, maxsplit=1, flags=re.I)
            title, company = parts[0].strip()[:255], parts[1].strip()[:255]
        elif not re.search(r"(19|20)\d{2}", second):
            company = second[:255]
    for ln in body[2:]:
        if ln.startswith(("•", "-", "·")) or len(ln) > 40:
            bullets.append(ln.lstrip("•·-* ").strip())
    summary = humanize_line(" ".join(bullets))[:2000]
    return {"title": title, "company": company, "location": location, "start": start, "end": end, "summary": summary}


def extract_linkedin_url(text: str) -> str | None:
    m = _LINKEDIN_RE.search(text or "")
    return m.group(0).rstrip("/")[:500] if m else None


def extract_website(text: str) -> str | None:
    for m in _URL_RE.finditer(text or ""):
        url = m.group(0).rstrip(".,)")
        if "linkedin.com" in url.lower():
            continue
        return url[:500]
    return None


def guess_city(text: str) -> str | None:
    for line in _lines(text)[:12]:
        if "@" in line or _PHONE_RE.search(line):
            continue
        if re.search(r"\b[A-Z][a-z]+,\s*[A-Z]{2}\b", line):
            return line.split(",")[0].strip()[:255]
        if re.search(r"\b[A-Z][a-z]+,\s*[A-Za-z\s]+\b", line) and len(line) < 80:
            return line.strip()[:255]
    return None


def format_user_information_block(intake: dict) -> str:
    parts: list[str] = []
    skills = intake.get("skills") or []
    if skills:
        parts.append("Skills: " + ", ".join(skills[:60]))
    for job in intake.get("work_history") or []:
        if not isinstance(job, dict):
            continue
        title = job.get("title") or ""
        company = job.get("company") or ""
        when = " — ".join(p for p in (job.get("start"), job.get("end")) if p)
        line = f"Work: {title} at {company}".strip()
        if when:
            line += f" ({when})"
        summary = (job.get("summary") or "").strip()
        if summary:
            line += ". " + summary
        parts.append(line)
    for ed in intake.get("education") or []:
        if not isinstance(ed, dict):
            continue
        degree = ed.get("degree") or ""
        field = ed.get("field") or ""
        school = ed.get("school") or ""
        when = ed.get("end_year") or ed.get("start_year") or ""
        label = ", ".join(p for p in (degree, field) if p)
        line = f"Education: {label} — {school}".strip(" —")
        if when:
            line += f" ({when})"
        parts.append(line)
    if intake.get("current_title") or intake.get("current_company"):
        parts.append(
            f"Current role: {intake.get('current_title') or ''} at {intake.get('current_company') or ''}".strip()
        )
    return "\n".join(parts)[:20000]


def _set_paragraph_text(paragraph: Paragraph, text: str) -> None:
    if not paragraph.runs:
        paragraph.add_run(text)
        return
    paragraph.runs[0].text = text
    for run in paragraph.runs[1:]:
        run.text = ""


def _insert_paragraph_after(paragraph: Paragraph, text: str) -> Paragraph:
    new_p = OxmlElement("w:p")
    paragraph._p.addnext(new_p)
    new_para = Paragraph(new_p, paragraph._parent)
    if text:
        new_para.add_run(text)
    return new_para


def _section_ranges(paragraphs: list[Paragraph]) -> dict[str, tuple[int, int]]:
    headers: list[tuple[int, str]] = []
    for i, para in enumerate(paragraphs):
        kind = section_kind(para.text)
        if kind:
            headers.append((i, kind))
    ranges: dict[str, tuple[int, int]] = {}
    for idx, (start_i, kind) in enumerate(headers):
        end_i = headers[idx + 1][0] if idx + 1 < len(headers) else len(paragraphs)
        ranges[kind] = (start_i, end_i)
    return ranges


def _apply_bullet_edits_to_paragraphs(paragraphs: list[Paragraph], edits: list[dict], resume_text: str) -> None:
    lower_resume = resume_text.lower()
    for edit in edits:
        find = str(edit.get("find") or "")
        repl = humanize_line(str(edit.get("replace") or ""))
        if len(find) < 12 or find.lower() not in lower_resume or not repl:
            continue
        for para in paragraphs:
            if find in para.text:
                _set_paragraph_text(para, para.text.replace(find, repl, 1))
                break


def _replace_section_lines(paragraphs: list[Paragraph], start: int, end: int, lines: list[str]) -> None:
    content = [i for i in range(start + 1, end)]
    if not content and lines:
        anchor = paragraphs[start]
        prev = anchor
        for line in lines:
            prev = _insert_paragraph_after(prev, line)
        return
    for j, idx in enumerate(content):
        _set_paragraph_text(paragraphs[idx], lines[j] if j < len(lines) else "")
    if len(lines) > len(content) and content:
        prev = paragraphs[content[-1]]
        for line in lines[len(content) :]:
            prev = _insert_paragraph_after(prev, line)


def skills_line_from_patch(patch: dict) -> str:
    direct = humanize_line(str(patch.get("skills_line") or ""))
    if direct:
        return direct
    order = [humanize_line(str(s)) for s in patch.get("skills_order") or [] if str(s).strip()]
    parts: list[str] = []
    seen: set[str] = set()
    for skill in order:
        key = skill.lower()
        if key not in seen:
            seen.add(key)
            parts.append(skill)
    for block in patch.get("subskills_display") or []:
        master = humanize_line(str(block.get("master") or ""))
        items = [humanize_line(str(x)) for x in block.get("items") or [] if str(x).strip()]
        if master and items:
            chunk = f"{master} ({', '.join(items[:6])})"
            if chunk.lower() not in seen:
                seen.add(chunk.lower())
                parts.append(chunk)
    return ", ".join(parts)


def apply_tailor_patch_to_docx(doc: Document, patch: dict, resume_text: str) -> None:
    paragraphs = list(doc.paragraphs)
    _apply_bullet_edits_to_paragraphs(paragraphs, patch.get("bullet_edits") or [], resume_text)

    summary_lines = [humanize_line(str(x)) for x in patch.get("summary_lines") or [] if str(x).strip()]
    skills_line = skills_line_from_patch(patch)
    ranges = _section_ranges(paragraphs)

    if summary_lines and "summary" in ranges:
        start, end = ranges["summary"]
        _replace_section_lines(paragraphs, start, end, summary_lines[:5])
    if skills_line and "skills" in ranges:
        start, end = ranges["skills"]
        _replace_section_lines(paragraphs, start, end, [skills_line])


def _lines_from_plain_text(text: str) -> list[str]:
    return text.replace("\r\n", "\n").split("\n")


def apply_tailor_patch_to_plain_lines(lines: list[str], patch: dict, resume_text: str) -> list[str]:
    joined = "\n".join(lines)
    lower = resume_text.lower()
    for edit in patch.get("bullet_edits") or []:
        find = str(edit.get("find") or "")
        repl = humanize_line(str(edit.get("replace") or ""))
        if len(find) >= 12 and find.lower() in lower and repl and find in joined:
            joined = joined.replace(find, repl, 1)
    lines = joined.split("\n")

    summary_lines = [humanize_line(str(x)) for x in patch.get("summary_lines") or [] if str(x).strip()]
    skills_line = skills_line_from_patch(patch)

    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        kind = section_kind(line)
        out.append(line)
        if kind == "summary" and summary_lines:
            i += 1
            while i < len(lines) and not section_kind(lines[i]):
                i += 1
            out.extend(summary_lines[:5])
            continue
        if kind == "skills" and skills_line:
            i += 1
            while i < len(lines) and not section_kind(lines[i]):
                i += 1
            out.append(skills_line)
            continue
        i += 1
    return out


def write_human_docx(doc: Document, path: Path) -> None:
    props = doc.core_properties
    props.author = ""
    props.title = ""
    props.subject = ""
    props.category = ""
    props.comments = ""
    props.keywords = ""
    props.last_modified_by = ""
    path.parent.mkdir(parents=True, exist_ok=True)
    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    with zipfile.ZipFile(buf, "r") as zin:
        out_buf = BytesIO()
        with zipfile.ZipFile(out_buf, "w", zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                if item.filename in {"docProps/custom.xml", "docMetadata/LabelInfo.xml"}:
                    continue
                zout.writestr(item, zin.read(item.filename))
        path.write_bytes(out_buf.getvalue())


_PHONE_RE = re.compile(
    r"(?:\+?\d{1,3}[\s.-]?)?(?:\(?\d{2,4}\)?[\s.-]?)?\d{3,4}[\s.-]?\d{3,4}(?:[\s.-]?\d{2,4})?"
)


def extract_phone(text: str) -> str | None:
    for line in (text or "").splitlines()[:25]:
        for match in _PHONE_RE.findall(line):
            digits = re.sub(r"\D", "", match)
            if 10 <= len(digits) <= 15:
                return match.strip()[:32]
    return None


def extract_summary_block(text: str) -> str | None:
    lines = [ln.strip() for ln in (text or "").splitlines()]
    for i, line in enumerate(lines):
        if section_kind(line) == "summary":
            chunk: list[str] = []
            for nxt in lines[i + 1 : i + 12]:
                if not nxt:
                    if chunk:
                        break
                    continue
                if section_kind(nxt):
                    break
                chunk.append(nxt)
            joined = humanize_line(" ".join(chunk))
            return joined[:5000] if joined else None
    return None


def guess_experience_years(text: str) -> int | None:
    spans: set[int] = set()
    now = 2026
    for m in re.finditer(
        r"\b(19|20)(\d{2})\s*[-–—]\s*(?:(19|20)(\d{2})|present|current|now)\b",
        (text or "").lower(),
    ):
        y_start = int(m.group(1) + m.group(2))
        if m.group(3):
            y_end = int(m.group(3) + m.group(4))
        else:
            y_end = now
        if 1970 <= y_start <= now and y_start <= y_end <= now + 1:
            spans.add(y_end - y_start)
    if spans:
        return min(max(spans), 60)
    m = re.search(r"\b(\d{1,2})\+?\s*years?\s+(?:of\s+)?experience\b", (text or "").lower())
    if m:
        return min(int(m.group(1)), 60)
    return None


def guess_name_from_text(text: str) -> tuple[str, str]:
    for line in (text or "").splitlines()[:8]:
        clean = re.sub(r"[^a-zA-Z\s.'-]", "", line).strip()
        if not clean or len(clean) > 80:
            continue
        lower = clean.lower()
        if any(x in lower for x in ("resume", "curriculum", "vitae", "phone", "email", "@", "http", "linkedin")):
            continue
        parts = clean.split()
        if 1 <= len(parts) <= 4 and all(p[0].isupper() for p in parts if p):
            if len(parts) == 1:
                return parts[0], ""
            return parts[0], " ".join(parts[1:])
    return "", ""


def guess_current_role(text: str) -> tuple[str | None, str | None]:
    """Best-effort title and company from the first experience block."""
    lines = [ln.strip() for ln in (text or "").splitlines() if ln.strip()]
    exp_idx = None
    for i, line in enumerate(lines):
        t = re.sub(r"[^a-zA-Z\s]", "", line).lower().strip()
        if t in {"experience", "work experience", "professional experience", "employment"}:
            exp_idx = i
            break
    if exp_idx is None:
        return None, None
    block = lines[exp_idx + 1 : exp_idx + 6]
    if not block:
        return None, None
    title = block[0][:255]
    company = None
    if len(block) > 1:
        second = block[1]
        if " at " in second.lower():
            parts = re.split(r"\s+at\s+", second, maxsplit=1, flags=re.I)
            if len(parts) == 2:
                title, company = parts[0].strip()[:255], parts[1].strip()[:255]
        elif not re.search(r"\b(19|20)\d{2}\b", second):
            company = second[:255]
    return title or None, company


def heuristic_profile_intake(text: str) -> dict:
    lines = _lines(text)
    first, last = guess_name_from_text(text)
    skills = guess_skills_from_text(text, [])
    summary = extract_summary_block(text)
    title, company = guess_current_role(text)
    years = guess_experience_years(text)
    edu_chunk = _slice_section(lines, "education", stop_kinds=frozenset({"experience", "skills", "summary"}))
    exp_chunk = _slice_section(lines, "experience", stop_kinds=frozenset({"education", "skills", "summary"}))
    education = _parse_education_lines(edu_chunk)
    work_history = _parse_experience_lines(exp_chunk)
    if not work_history and title:
        work_history = [{"title": title, "company": company or "", "location": "", "start": "", "end": "Present", "summary": ""}]
    has_masters = any(
        "master" in (e.get("degree") or "").lower() or "mba" in (e.get("degree") or "").lower() for e in education
    )
    headline_parts = [p for p in (title, ", ".join(skills[:4]) if skills else "") if p]
    headline = " · ".join(headline_parts)[:255] if headline_parts else None
    name = " ".join(p for p in (first, last) if p).strip()
    cover = ""
    if summary or title:
        cover = (
            f"Dear Hiring Manager,\n\n"
            f"I am writing to express my interest in opportunities that match my background"
            f"{f' as a {title}' if title else ''}. "
            f"{summary or 'Please find my resume attached for your review.'}\n\n"
            f"Thank you for your time and consideration.\n\n"
            f"{'Sincerely,' + chr(10) + name if name else 'Best regards,'}"
        )
    intake = {
        "first_name": first,
        "last_name": last,
        "middle_name": "",
        "phone": extract_phone(text),
        "headline": headline,
        "summary": summary,
        "current_title": title,
        "current_company": company,
        "experience_years": years,
        "skills": skills,
        "preferred_roles": [title] if title else [],
        "preferred_locations": [],
        "cover_letter": cover[:10000] if cover else "",
        "education": education,
        "work_history": work_history,
        "current_city": guess_city(text),
        "linkedIn": extract_linkedin_url(text),
        "website": extract_website(text),
        "has_masters": has_masters,
    }
    intake["user_information_all"] = format_user_information_block(intake)
    return intake


def render_tailored_docx(
    source_path: Path,
    patch: dict,
    out_path: Path,
    *,
    resume_text: str,
    template_id: str = "modern",
) -> None:
    from backend.app.services import resume_templates

    if source_path.suffix.lower() == ".docx":
        doc = Document(str(source_path))
        if patch:
            apply_tailor_patch_to_docx(doc, patch, resume_text)
        resume_templates.apply_template_to_document(doc, template_id)
        write_human_docx(doc, out_path)
        return

    lines = apply_tailor_patch_to_plain_lines(_lines_from_plain_text(resume_text), patch, resume_text)
    doc = Document()
    for line in lines:
        doc.add_paragraph(line if line.strip() else "")
    resume_templates.apply_template_to_document(doc, template_id)
    write_human_docx(doc, out_path)
